---
# The retries are for random lock failures.
- name: install build-essential and musl
  become: True
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items:
    - build-essential
    # - musl
    # - musl-tools
  register: result
  until: result is succeeded
  retries: 3
  delay: 5

    # rustup target add x86_64-unknown-linux-musl
- name: install rustup
  ansible.builtin.shell: |
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh  -s -- --default-toolchain stable -y
    source $HOME/.cargo/env
  args:
    creates: "{{ ansible_env.HOME }}/.cargo/env"
    executable: /bin/bash
